name: "Monitor de Impressão 3D"
description: "Analisa sua impressão 3D via câmera usando IA (Gemini) e alerta no Telegram caso detecte falhas."
version: "1.0.0"
slug: "monitor_impressao_3d"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7

homeassistant_api: true
auth_api: true

options:
  gemini_api_key: ""
  camera_entity: "camera.motioneye_camera"
  intervalo_minutos: 2
  severidade_alerta: "media"
  telegram_bot_token: ""
  telegram_chat_id: ""
  octoprint_url: "http://192.168.1.100"
  octoprint_api_key: ""
  pausar_em_falha_alta: true
  octoprint_entity: "sensor.octoprint_current_state"

schema:
  gemini_api_key: str
  camera_entity: str
  intervalo_minutos: int(1,60)
  severidade_alerta: list(baixa|media|alta)
  telegram_bot_token: str
  telegram_chat_id: str
  octoprint_url: str
  octoprint_api_key: str
  pausar_em_falha_alta: bool
  octoprint_entity: str
